language: php

sudo: false

cache:
  directories:
    - $HOME/.composer/cache

matrix:
  include:
    - php: 7.0
    #- php: 7.1

before_script:
  - travis_retry composer install --prefer-source --no-interaction --dev

script:
  - bin/phpstan analyse src --level=1
  - bin/phpspec run --format=pretty
  - bin/phpunit --coverage-clover=coverage.xml
  - wget https://phar.phpunit.de/phpcov.phar && php phpcov.phar merge /tmp --clover coverage.xml

after_success:
  - bash <(curl -s https://codecov.io/bash)