# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
    app.repository.abstinence:
        class: SimpleHabits\Infrastructure\Domain\Model\Abstinence\DoctrineAbstinenceRepository
        arguments:
            - '@doctrine.orm.entity_manager'

    app.repository.goal:
        class: SimpleHabits\Infrastructure\Domain\Model\Goal\DoctrineGoalRepository
        arguments:
            - '@doctrine.orm.entity_manager'

    app.create_new_abstinence_handler:
        class: SimpleHabits\Application\Handler\CreateNewAbstinenceHandler
        arguments:
            - '@app.repository.abstinence'
        tags:
            - { name: tactician.handler, command: SimpleHabits\Application\Command\CreateNewAbstinenceCommand }

    app.add_violation_handler:
        class: SimpleHabits\Application\Handler\AddViolationHandler
        arguments:
            - '@app.repository.abstinence'
        tags:
            - { name: tactician.handler, command: SimpleHabits\Application\Command\AddViolationCommand }

    app.remove_abstinence_handler:
        class: SimpleHabits\Application\Handler\RemoveAbstinenceHandler
        arguments:
            - '@app.repository.abstinence'
        tags:
            - { name: tactician.handler, command: SimpleHabits\Application\Command\RemoveAbstinenceCommand }

    app.create_new_goal_handler:
        class: SimpleHabits\Application\Handler\Goal\CreateNewGoalHandler
        arguments:
            - '@app.repository.goal'
        tags:
            - { name: tactician.handler, command: SimpleHabits\Application\Command\Goal\CreateNewGoalCommand }

    app.remove_goal_handler:
        class: SimpleHabits\Application\Handler\Goal\RemoveGoalHandler
        arguments:
            - '@app.repository.goal'
        tags:
            - { name: tactician.handler, command: SimpleHabits\Application\Command\Goal\RemoveGoalCommand }

    app.add_goal_step_handler:
        class: SimpleHabits\Application\Handler\Goal\AddGoalStepHandler
        arguments:
            - '@app.repository.goal'
        tags:
            - { name: tactician.handler, command: SimpleHabits\Application\Command\Goal\AddGoalStepCommand }